
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
// import { supabase } from '@/lib/customSupabaseClient';

const usePageTracking = () => {
  const location = useLocation();

  useEffect(() => {
    const trackPageVisit = async () => {
      try {
        // NOTE: page_visitors table does not exist in the current schema.
        // Tracking logic is commented out to prevent errors.
        
        /*
        // Fetch IP address (simple external service)
        let ipAddress = 'unknown';
        try {
          const res = await fetch('https://api.ipify.org?format=json');
          if (res.ok) {
            const data = await res.json();
            ipAddress = data.ip;
          }
        } catch (e) {
          console.warn('Could not fetch IP address', e);
        }

        const userAgent = navigator.userAgent;
        const pagePath = location.pathname;

        await supabase.from('page_visitors').insert([
          {
            page_path: pagePath,
            user_agent: userAgent,
            ip_address: ipAddress,
            // timestamp is auto-generated by default in DB
          },
        ]);
        */
       // console.log('Page tracking skipped: page_visitors table missing');
      } catch (error) {
        console.error('Error tracking page visit:', error);
      }
    };

    trackPageVisit();
  }, [location]);

  return null;
};

export default usePageTracking;
